### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by mhmrahmati** [afiqharith/SocialDistancingViolationSystem-SODV#1]
Hi, I got the bellow error when i wanted to run the code.

`Traceback (most recent call last):
  File "social_distancing_violation_system.py", line 58, in <module>
    class MainCtrl:
  File "social_distancing_violation_system.py", line 185, in MainCtrl
    def get_roi_frame(self, frame, coordinate: list[tuple]):
TypeError: 'type' object is not subscriptable`

I have python version 3.8.0 (2019) and all requirements.txt have installed successfully. is it about python version?

**Comment by afiqharith** [comment]
Hi @mhmrahmati , I think it related to the python version. You may try to use `from __future__ import annotations` to fix the issue.
You may also refer this [link](https://stackoverflow.com/questions/63460126/typeerror-type-object-is-not-subscriptable-in-a-function-signature) regarding the issue.
